strategy:
  matrix:
    3.8-rc-stretch:
      azureImage: 'ubuntu-16.04'
      buildContext: '3.8-rc/stretch'
      dockerTag: 'azure-pipelines/python:3.8-rc-stretch'
    3.8-rc-stretch-slim:
      azureImage: 'ubuntu-16.04'
      buildContext: '3.8-rc/stretch/slim'
      dockerTag: 'azure-pipelines/python:3.8-rc-stretch-slim'
    3.8-rc-alpine3.9:
      azureImage: 'ubuntu-16.04'
      buildContext: '3.8-rc/alpine3.9'
      dockerTag: 'azure-pipelines/python:3.8-rc-alpine3.9'
    3.8-rc-windows-windowsservercore-1803:
      azureImage: 'win1803'
      buildContext: '3.8-rc/windows/windowsservercore-1803'
      dockerTag: 'azure-pipelines/python:3.8-rc-windows-windowsservercore-1803'
    3.7-stretch:
      azureImage: 'ubuntu-16.04'
      buildContext: '3.7/stretch'
      dockerTag: 'azure-pipelines/python:3.7-stretch'
    3.7-stretch-slim:
      azureImage: 'ubuntu-16.04'
      buildContext: '3.7/stretch/slim'
      dockerTag: 'azure-pipelines/python:3.7-stretch-slim'
    3.7-alpine3.9:
      azureImage: 'ubuntu-16.04'
      buildContext: '3.7/alpine3.9'
      dockerTag: 'azure-pipelines/python:3.7-alpine3.9'
    3.7-alpine3.8:
      azureImage: 'ubuntu-16.04'
      buildContext: '3.7/alpine3.8'
      dockerTag: 'azure-pipelines/python:3.7-alpine3.8'
    3.7-windows-windowsservercore-1803:
      azureImage: 'win1803'
      buildContext: '3.7/windows/windowsservercore-1803'
      dockerTag: 'azure-pipelines/python:3.7-windows-windowsservercore-1803'
    3.6-stretch:
      azureImage: 'ubuntu-16.04'
      buildContext: '3.6/stretch'
      dockerTag: 'azure-pipelines/python:3.6-stretch'
    3.6-stretch-slim:
      azureImage: 'ubuntu-16.04'
      buildContext: '3.6/stretch/slim'
      dockerTag: 'azure-pipelines/python:3.6-stretch-slim'
    3.6-jessie:
      azureImage: 'ubuntu-16.04'
      buildContext: '3.6/jessie'
      dockerTag: 'azure-pipelines/python:3.6-jessie'
    3.6-jessie-slim:
      azureImage: 'ubuntu-16.04'
      buildContext: '3.6/jessie/slim'
      dockerTag: 'azure-pipelines/python:3.6-jessie-slim'
    3.6-alpine3.9:
      azureImage: 'ubuntu-16.04'
      buildContext: '3.6/alpine3.9'
      dockerTag: 'azure-pipelines/python:3.6-alpine3.9'
    3.6-alpine3.8:
      azureImage: 'ubuntu-16.04'
      buildContext: '3.6/alpine3.8'
      dockerTag: 'azure-pipelines/python:3.6-alpine3.8'
    3.6-windows-windowsservercore-1803:
      azureImage: 'win1803'
      buildContext: '3.6/windows/windowsservercore-1803'
      dockerTag: 'azure-pipelines/python:3.6-windows-windowsservercore-1803'
    3.5-stretch:
      azureImage: 'ubuntu-16.04'
      buildContext: '3.5/stretch'
      dockerTag: 'azure-pipelines/python:3.5-stretch'
    3.5-stretch-slim:
      azureImage: 'ubuntu-16.04'
      buildContext: '3.5/stretch/slim'
      dockerTag: 'azure-pipelines/python:3.5-stretch-slim'
    3.5-jessie:
      azureImage: 'ubuntu-16.04'
      buildContext: '3.5/jessie'
      dockerTag: 'azure-pipelines/python:3.5-jessie'
    3.5-jessie-slim:
      azureImage: 'ubuntu-16.04'
      buildContext: '3.5/jessie/slim'
      dockerTag: 'azure-pipelines/python:3.5-jessie-slim'
    3.5-alpine3.9:
      azureImage: 'ubuntu-16.04'
      buildContext: '3.5/alpine3.9'
      dockerTag: 'azure-pipelines/python:3.5-alpine3.9'
    3.5-alpine3.8:
      azureImage: 'ubuntu-16.04'
      buildContext: '3.5/alpine3.8'
      dockerTag: 'azure-pipelines/python:3.5-alpine3.8'
    2.7-stretch:
      azureImage: 'ubuntu-16.04'
      buildContext: '2.7/stretch'
      dockerTag: 'azure-pipelines/python:2.7-stretch'
    2.7-stretch-slim:
      azureImage: 'ubuntu-16.04'
      buildContext: '2.7/stretch/slim'
      dockerTag: 'azure-pipelines/python:2.7-stretch-slim'
    2.7-jessie:
      azureImage: 'ubuntu-16.04'
      buildContext: '2.7/jessie'
      dockerTag: 'azure-pipelines/python:2.7-jessie'
    2.7-jessie-slim:
      azureImage: 'ubuntu-16.04'
      buildContext: '2.7/jessie/slim'
      dockerTag: 'azure-pipelines/python:2.7-jessie-slim'
    2.7-alpine3.9:
      azureImage: 'ubuntu-16.04'
      buildContext: '2.7/alpine3.9'
      dockerTag: 'azure-pipelines/python:2.7-alpine3.9'
    2.7-alpine3.8:
      azureImage: 'ubuntu-16.04'
      buildContext: '2.7/alpine3.8'
      dockerTag: 'azure-pipelines/python:2.7-alpine3.8'
    2.7-windows-windowsservercore-1803:
      azureImage: 'win1803'
      buildContext: '2.7/windows/windowsservercore-1803'
      dockerTag: 'azure-pipelines/python:2.7-windows-windowsservercore-1803'

pool:
  vmImage: $(azureImage)

steps:
- bash: |
    set -Eeuo pipefail -x
    source <(wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh')
  displayName: 'Apply pgp-happy-eyeballs'
  condition: eq( variables['Agent.OS'], 'Linux' )

- bash: |
    set -Eeuo pipefail -x
    docker build -t '$(dockerTag)' .
  workingDirectory: $(buildContext)
  displayName: 'Build $(dockerTag)'

- bash: |
    set -Eeuo pipefail -x
    docker run --rm '$(dockerTag)' python --version
  displayName: 'Basic smoke tests'

- bash: |
    set -Eeuo pipefail -x
    git clone --depth 1 https://github.com/docker-library/official-images.git ~/official-images
    ~/official-images/test/run.sh '$(dockerTag)'
  displayName: 'Run tests'
  condition: eq( variables['Agent.OS'], 'Linux' ) # TODO get tests running on Windows too (and ditch the basic smoke tests)
